# Generated by Django 5.0.7 on 2024-07-12 08:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Token', models.CharField(max_length=100)),
                ('Slug', models.SlugField(unique=True)),
                ('Content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('Image', models.ImageField(null=True, upload_to='Imgs')),
                ('Date', models.DateField(auto_now=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
